[package]
name = "knausio"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-files = "0.6.6"
serde_json = "1.0.135"
serde = { version = "1.0.217", features = ["derive"] }
diesel = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15"