# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
filter = {except_tables=["posts"]}

[print_schema.blog]
file="src/domain/blog/schema.rs"
filter = {only_tables=["posts"]}

[migrations_directory]
dir = "/home/pknaus3/Projects/knaus.io/migrations"
